name: OWPE-Events
version: 0.0.1
main: CJMustard1452\OWPE_Events\Main
api: 3.28.0

commands:
  oevent:
    description: Ownage event commands
    permission: owpe-eventscommand

permissions:
  owpe-eventscommand:
    default: op
    description: Ownage Event Permissions
